export { Dec, DECIMAL_PRECISION, formatDecimal, parseDecimal, type DecimalString } from './decimal';
export {
  change,
  deriveMetrics,
  share,
  sumDecimals,
  sumWithGaps,
  type Coverage,
  type DerivedMetrics,
  type MetricTotals,
} from './metrics';
export {
  AD_PRODUCTS,
  ATTRIBUTED_FIELDS,
  METRIC_AVAILABILITY,
  METRIC_COLUMNS,
  METRICS_LEVELS,
  selectAttribution,
  summarizeAttribution,
  type AdProduct,
  type AttributedField,
  type AttributionBasis,
  type AttributionSelection,
  type AttributionSetting,
  type AttributionSummary,
  type MetricColumn,
  type MetricsLevel,
  type SelectAttributionInput,
} from './attribution';
export { convertAmount, type DailyRates } from './fx';
export {
  buildNgrams,
  classifySearchTerm,
  classifySearchTermsAcrossTargets,
  comparableSearchTerm,
  createProtectedTermMatcher,
  isProtectedSearchTerm,
  NGRAM_SIZES,
  SEARCH_TERM_CLASSES,
  SEARCH_TERM_WATCH_REASONS,
  tokenizeSearchTerm,
  type Ngram,
  type NgramSize,
  type SearchTermAcrossTargets,
  type SearchTermClass,
  type SearchTermClassification,
  type SearchTermRules,
  type SearchTermSums,
  type SearchTermWatchReason,
} from './search-terms';
export {
  AD_CHANGE_WARNING_COUNT,
  AD_CHANGE_WARNING_PERCENT,
  checkAdChanges,
  NEGATIVE_KEYWORD_MAX_LENGTH,
  NEGATIVE_KEYWORD_MAX_WORDS,
  type AdChangeCheckInput,
  type AdChangeCheckResult,
  type AdChangeLimitField,
  type AdChangeLimitLookup,
  type AdChangeLimitViolation,
} from './ad-changes';
export * from './naming';
export * from './plan';
export {
  BID_STACK_PLACEMENTS,
  BID_STACK_STRATEGIES,
  MAX_BID_ADJUSTMENT_PERCENT,
  MAX_BID_STACK_AUDIENCES,
  simulateBidStack,
  type BidStackInput,
  type BidStackPlacement,
  type BidStackResult,
  type BidStackRow,
  type BidStackStrategy,
} from './bid-stack';
