/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Erreichbarkeit von API und Datenbank */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API und Datenbank sind erreichbar. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Die Datenbank ist nicht erreichbar. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Angemeldeter Nutzer mit Organisationen, Rechten und Einstellungen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nutzerkontext für die App-Shell. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Einstellungen des angemeldeten Nutzers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Einstellungen (Defaults, falls nichts gespeichert ist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Einstellungen vollständig ersetzen */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            responses: {
                /** @description Gespeicherte Einstellungen. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ui-state/{scope}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gespeicherten UI-Zustand lesen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gespeicherter Wert oder `null`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UiState"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** UI-Zustand speichern (kein Audit-Event: reiner Darstellungszustand) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UiStatePut"];
                };
            };
            responses: {
                /** @description Gespeicherter Wert. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UiState"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "error";
            /** @enum {string} */
            db: "ok" | "error";
            version: string;
        };
        Me: {
            user: {
                id: string;
                email: string;
                name: string;
                /** @enum {string} */
                role: "user" | "superadmin";
            };
            organizations: {
                id: string;
                name: string;
                slug: string;
                type: string;
                /** @enum {string} */
                role: "admin" | "editor" | "viewer";
            }[];
            activeOrganizationId: string | null;
            features: {
                dashboard: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                "sp-explorer": {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                changes: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                tags: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                tools: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                budgets: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                automations: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                goals: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                profit: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                "dsp-explorer": {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
            };
            preferences: components["schemas"]["Settings"];
        };
        Settings: {
            /** @enum {string} */
            theme: "system" | "light" | "dark";
            /** @enum {string} */
            locale: "de-DE" | "en-GB" | "en-US";
            /** @enum {string} */
            density: "comfortable" | "compact";
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        UiState: {
            /** @description Beliebiger JSON-Wert */
            value?: unknown;
        };
        UiStatePut: {
            /** @description Beliebiger JSON-Wert */
            value: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
