/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Erreichbarkeit von API und Datenbank */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API und Datenbank sind erreichbar. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Die Datenbank ist nicht erreichbar. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Angemeldeter Nutzer mit Organisationen, Rechten und Einstellungen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nutzerkontext für die App-Shell. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Einstellungen des angemeldeten Nutzers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Einstellungen (Defaults, falls nichts gespeichert ist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Einstellungen vollständig ersetzen */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            responses: {
                /** @description Gespeicherte Einstellungen. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ui-state/{scope}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gespeicherten UI-Zustand lesen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gespeicherter Wert oder `null`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UiState"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** UI-Zustand speichern (kein Audit-Event: reiner Darstellungszustand) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UiStatePut"];
                };
            };
            responses: {
                /** @description Gespeicherter Wert. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UiState"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/amazon/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Amazon-Ads-Konto verbinden oder neu verbinden (nur Admin)
         * @description Liefert die Einwilligungs-URL mit signiertem, einmal verwendbarem `state` (10 Minuten gültig). Amazon leitet danach auf `/api/amazon/oauth/callback` zurück, der Callback auf `/admin/connections?oauth=<Ergebnis>`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AmazonOAuthStart"];
                };
            };
            responses: {
                /** @description Einwilligungs-URL. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AmazonOAuthRedirect"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Connection nicht gefunden. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connections der aktiven Organisation (nur Admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connections, älteste zuerst. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionList"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profil-Sync jetzt einplanen (nur Admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync eingeplant. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncQueued"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht gefunden. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Connection braucht zuerst ein Neu-Verbinden. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile einer Connection inkl. ausgeblendeter und entfernter (nur Admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile nach Land und Name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileList"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht gefunden. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Profil einem Client zuordnen oder ausblenden (nur Admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfilePatch"];
                };
            };
            responses: {
                /** @description Geändertes Profil. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht gefunden. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients der aktiven Organisation (nur Admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clients nach Name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientList"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Client anlegen (nur Admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientCreate"];
                };
            };
            responses: {
                /** @description Angelegter Client. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Slug in der Organisation vergeben. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Client umbenennen (nur Admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientPatch"];
                };
            };
            responses: {
                /** @description Geänderter Client. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Client nicht gefunden. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Slug in der Organisation vergeben. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Letzte 100 Jobläufe der aktiven Organisation (Sync-Status, nur Admin) */
        get: {
            parameters: {
                query?: {
                    job?: "token-refresh" | "profiles-sync" | "entities-sync" | "reports-sync" | "amazon-requests-poll" | "fx-rates-sync";
                    status?: "running" | "success" | "failed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Jobläufe, neueste zuerst. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobRunList"];
                    };
                };
                /** @description Ungültiger Filter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Keine Admin-Rolle. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auswahl der Filterleiste: sichtbare Clients und Profile, wählbare Währungen, Stand der Kurse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FilterOptionsRequest"];
                };
            };
            responses: {
                /** @description Ergebnis. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilterOptionsResponse"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Feature nicht gebucht oder kein Recht. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/explorer/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explorer: Zeilen einer Ebene mit Vergleich und Summenzeile (höchstens 10 000 Zeilen) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExplorerRowsRequest"];
                };
            };
            responses: {
                /** @description Ergebnis. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExplorerRowsResponse"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Feature nicht gebucht oder kein Recht. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/asin-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ASIN-Quick-Tool: Product Ads zu ASINs oder SKUs mit Kennzahlen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AsinSearchRequest"];
                };
            };
            responses: {
                /** @description Ergebnis. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExplorerRowsResponse"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Feature nicht gebucht oder kein Recht. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tagesverlauf der Auswahl in der Anzeigewährung (Chart, Hero-Kachel) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TimeSeriesRequest"];
                };
            };
            responses: {
                /** @description Ergebnis. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeSeriesResponse"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Feature nicht gebucht oder kein Recht. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dashboard: Summen gesamt und je Client, Profil und Ad-Typ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnalyticsQuery"];
                };
            };
            responses: {
                /** @description Ergebnis. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
                /** @description Ungültige Eingabe. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Nicht angemeldet. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Feature nicht gebucht oder kein Recht. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "error";
            /** @enum {string} */
            db: "ok" | "error";
            version: string;
        };
        Me: {
            user: {
                id: string;
                email: string;
                name: string;
                /** @enum {string} */
                role: "user" | "superadmin";
            };
            organizations: {
                id: string;
                name: string;
                slug: string;
                type: string;
                /** @enum {string} */
                role: "admin" | "editor" | "viewer";
            }[];
            activeOrganizationId: string | null;
            features: {
                dashboard: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                "sp-explorer": {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                changes: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                tags: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                tools: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                budgets: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                automations: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                goals: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                profit: {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
                "dsp-explorer": {
                    view: boolean;
                    write: boolean;
                    entitled: boolean;
                };
            };
            preferences: components["schemas"]["Settings"];
        };
        Settings: {
            /** @enum {string} */
            theme: "system" | "light" | "dark";
            /** @enum {string} */
            locale: "de-DE" | "en-GB" | "en-US";
            /** @enum {string} */
            density: "comfortable" | "compact";
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        UiState: {
            /** @description Beliebiger JSON-Wert */
            value?: unknown;
        };
        UiStatePut: {
            /** @description Beliebiger JSON-Wert */
            value: unknown;
        };
        AmazonOAuthRedirect: {
            url: string;
        };
        AmazonOAuthStart: {
            /** @enum {string} */
            region?: "eu" | "na" | "fe";
            /** Format: uuid */
            connectionId?: string;
        };
        ConnectionList: {
            connections: components["schemas"]["Connection"][];
        };
        Connection: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            provider: "amazon_ads";
            /** @enum {string|null} */
            region: "eu" | "na" | "fe" | null;
            externalAccountId: string;
            externalAccountEmail: string | null;
            /** @enum {string} */
            status: "active" | "reauth_required" | "error";
            /** Format: date-time */
            lastRefreshedAt: string | null;
            /** Format: date-time */
            consentedAt: string | null;
            /** Format: date-time */
            refreshTokenExpiresAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SyncQueued: {
            /** @enum {string} */
            status: "queued";
        };
        ProfileList: {
            profiles: components["schemas"]["Profile"][];
        };
        Profile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            connectionId: string;
            /** Format: uuid */
            clientId: string | null;
            amazonProfileId: string;
            amazonAccountId: string | null;
            accountName: string;
            countryCode: string;
            currencyCode: string;
            timezone: string;
            marketplaceId: string | null;
            accountType: string;
            isHidden: boolean;
            /** Format: date-time */
            removedAt: string | null;
            /** Format: date-time */
            syncedAt: string | null;
            /** Format: date */
            metricsImportedThrough: string | null;
        };
        ProfilePatch: {
            /** Format: uuid */
            clientId?: string | null;
            isHidden?: boolean;
        };
        ClientList: {
            clients: components["schemas"]["Client"][];
        };
        Client: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClientCreate: {
            name: string;
            slug?: string;
        };
        ClientPatch: {
            name?: string;
            slug?: string;
        };
        JobRunList: {
            jobRuns: components["schemas"]["JobRun"][];
        };
        JobRun: {
            /** Format: uuid */
            id: string;
            job: string;
            scope: string | null;
            connection: {
                /** Format: uuid */
                id: string;
                externalAccountId: string;
                externalAccountEmail: string | null;
            } | null;
            /** @enum {string} */
            status: "running" | "success" | "failed";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            error: string | null;
            counters: {
                [key: string]: number;
            };
        };
        FilterOptionsResponse: {
            clients: {
                id: string;
                name: string;
                slug: string;
            }[];
            profiles: {
                id: string;
                amazonProfileId: string;
                accountName: string;
                countryCode: string;
                currencyCode: string;
                timezone: string;
                accountType: string;
                clientId: string | null;
            }[];
            currencies: string[];
            /** Format: date */
            fxRatesThrough: string | null;
            fxRatesStale: boolean;
        };
        FilterOptionsRequest: Record<string, never>;
        ExplorerRowsResponse: {
            meta: components["schemas"]["AnalyticsMeta"];
            rows: components["schemas"]["ExplorerRow"][];
            totalRows: number;
            truncated: boolean;
            maxRows: number;
            total: components["schemas"]["MetricsTotal"];
        };
        AnalyticsMeta: {
            currency: string;
            converted: boolean;
            missingFxCurrencies: string[];
            /** Format: date */
            dataThrough: string | null;
            /** Format: date */
            provisionalFrom: string | null;
            /** Format: date */
            earliestDate: string | null;
            profilesWithoutData: number;
        };
        ExplorerRow: {
            id: string;
            profileId: string;
            accountName: string;
            countryCode: string;
            currencyCode: string;
            adProduct: string | null;
            name: string | null;
            state: string | null;
            removed: boolean;
            placeholder: boolean;
            hasMetrics: boolean;
            attributes: {
                [key: string]: unknown;
            };
            current: components["schemas"]["PeriodMetrics"];
            comparison: components["schemas"]["PeriodMetrics"];
            change: {
                impressions?: string | null;
                clicks?: string | null;
                cost?: string | null;
                sales?: string | null;
                purchases?: string | null;
                units?: string | null;
                ctr?: string | null;
                cpc?: string | null;
                cvr?: string | null;
                acos?: string | null;
                roas?: string | null;
                cpm?: string | null;
                vcpm?: string | null;
            } | null;
            attribution: components["schemas"]["AttributionSummary"];
        };
        PeriodMetrics: {
            sums: components["schemas"]["MetricSums"];
            derived: components["schemas"]["DerivedMetrics"];
        } | null;
        MetricSums: {
            impressions: string | null;
            clicks: string | null;
            cost: string | null;
            sales: string | null;
            purchases: string | null;
            units: string | null;
            salesSameSku: string | null;
            purchasesSameSku: string | null;
            unitsSameSku: string | null;
            viewableImpressions: string | null;
            viewableCost: string | null;
        };
        DerivedMetrics: {
            ctr: string | null;
            cpc: string | null;
            cvr: string | null;
            acos: string | null;
            roas: string | null;
            cpm: string | null;
            vcpm: string | null;
        };
        AttributionSummary: {
            mixed: boolean;
            sameSkuMixed: boolean;
            coverage: {
                /** @enum {string} */
                sales: "full" | "partial" | "none";
                /** @enum {string} */
                purchases: "full" | "partial" | "none";
                /** @enum {string} */
                units: "full" | "partial" | "none";
                /** @enum {string} */
                salesSameSku: "full" | "partial" | "none";
                /** @enum {string} */
                purchasesSameSku: "full" | "partial" | "none";
                /** @enum {string} */
                unitsSameSku: "full" | "partial" | "none";
            };
        } | null;
        MetricsTotal: {
            current: components["schemas"]["PeriodMetrics"];
            comparison: components["schemas"]["PeriodMetrics"];
            change: components["schemas"]["MetricChanges"];
            attribution: components["schemas"]["AttributionSummary"];
        } | null;
        MetricChanges: {
            impressions: components["schemas"]["MetricChange"];
            clicks: components["schemas"]["MetricChange"];
            cost: components["schemas"]["MetricChange"];
            sales: components["schemas"]["MetricChange"];
            purchases: components["schemas"]["MetricChange"];
            units: components["schemas"]["MetricChange"];
            ctr: components["schemas"]["MetricChange"];
            cpc: components["schemas"]["MetricChange"];
            cvr: components["schemas"]["MetricChange"];
            acos: components["schemas"]["MetricChange"];
            roas: components["schemas"]["MetricChange"];
            cpm: components["schemas"]["MetricChange"];
            vcpm: components["schemas"]["MetricChange"];
        } | null;
        MetricChange: {
            absolute: string | null;
            relative: string | null;
        };
        ExplorerRowsRequest: {
            clientIds?: string[];
            withoutClient?: boolean;
            profileIds?: string[];
            adProducts?: ("SPONSORED_PRODUCTS" | "SPONSORED_BRANDS" | "SPONSORED_DISPLAY")[];
            period: components["schemas"]["DateRange"];
            comparison?: components["schemas"]["DateRange"] & (Record<string, never> | null);
            /** @default auto */
            currency: "auto" | string;
            /**
             * @default console
             * @enum {string}
             */
            attribution: "console" | "clicks14d";
            /** @enum {string} */
            level: "portfolio" | "campaign" | "adGroup" | "target" | "productAd" | "searchTerm" | "negative";
            filter?: {
                portfolioIds?: string[];
                campaignIds?: string[];
                adGroupIds?: string[];
                includeRemoved?: boolean;
            };
        };
        DateRange: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        AsinSearchRequest: {
            clientIds?: string[];
            withoutClient?: boolean;
            profileIds?: string[];
            adProducts?: ("SPONSORED_PRODUCTS" | "SPONSORED_BRANDS" | "SPONSORED_DISPLAY")[];
            period: components["schemas"]["DateRange"];
            comparison?: components["schemas"]["DateRange"] & (Record<string, never> | null);
            /** @default auto */
            currency: "auto" | string;
            /**
             * @default console
             * @enum {string}
             */
            attribution: "console" | "clicks14d";
            terms: string[];
        };
        TimeSeriesResponse: {
            meta: components["schemas"]["AnalyticsMeta"];
            days: {
                /** Format: date */
                date: string;
                sums: components["schemas"]["MetricSums"];
                derived: components["schemas"]["DerivedMetrics"];
            }[];
            comparisonDays: {
                /** Format: date */
                date: string;
                sums: components["schemas"]["MetricSums"];
                derived: components["schemas"]["DerivedMetrics"];
            }[];
            attribution: components["schemas"]["AttributionSummary"];
        };
        TimeSeriesRequest: {
            clientIds?: string[];
            withoutClient?: boolean;
            profileIds?: string[];
            adProducts?: ("SPONSORED_PRODUCTS" | "SPONSORED_BRANDS" | "SPONSORED_DISPLAY")[];
            period: components["schemas"]["DateRange"];
            comparison?: components["schemas"]["DateRange"] & (Record<string, never> | null);
            /** @default auto */
            currency: "auto" | string;
            /**
             * @default console
             * @enum {string}
             */
            attribution: "console" | "clicks14d";
            /**
             * @default campaign
             * @enum {string}
             */
            level: "portfolio" | "campaign" | "adGroup" | "target" | "productAd" | "searchTerm";
            filter?: {
                portfolioIds?: string[];
                campaignIds?: string[];
                adGroupIds?: string[];
                includeRemoved?: boolean;
            };
            entityIds?: string[];
        };
        DashboardResponse: {
            meta: components["schemas"]["AnalyticsMeta"];
            total: components["schemas"]["MetricsTotal"];
            byClient: components["schemas"]["DashboardGroup"][];
            byProfile: components["schemas"]["DashboardGroup"][];
            byAdProduct: components["schemas"]["DashboardGroup"][];
            /** Format: date */
            fxRatesThrough: string | null;
            fxRatesStale: boolean;
        };
        DashboardGroup: {
            current: components["schemas"]["PeriodMetrics"];
            comparison: components["schemas"]["PeriodMetrics"];
            change: components["schemas"]["MetricChanges"];
            attribution: components["schemas"]["AttributionSummary"];
            key: string | null;
            label: string | null;
            countryCode?: string;
            currencyCode?: string;
        };
        AnalyticsQuery: {
            clientIds?: string[];
            withoutClient?: boolean;
            profileIds?: string[];
            adProducts?: ("SPONSORED_PRODUCTS" | "SPONSORED_BRANDS" | "SPONSORED_DISPLAY")[];
            period: components["schemas"]["DateRange"];
            comparison?: components["schemas"]["DateRange"] & (Record<string, never> | null);
            /** @default auto */
            currency: "auto" | string;
            /**
             * @default console
             * @enum {string}
             */
            attribution: "console" | "clicks14d";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
